
# frequency: control loop frequenct (Hz)
frequency: 300.0 

# Kinematic configuration for the MIT cheetah 
# initial postion: x,y,z
# initial orientation: x,y,z,w
initial_pose:
  position: [0.0, 0.0, 0.06] 
  orientation: [0.0, 0.0, 0.0, 1.0]

# t_stance: time in stance phase (s)
# t_swing: time in swing phase (s)
# height: max height achieved at center of leg swing trajectory (m)
# gait_offset_phases: for legs [RL FL RR FR] in domain [0 1]
gait:
  t_stance: 0.8
  t_swing: 0.18
  height: 0.08
  gait_offset_phases: [0.0, 0.5, 0.5, 0.0]

# base_link: base_link frame
links:
  base_link: "trunk"

# num_joints: total number of joints
# joint_names: joint names
# joint_actuator_names: joint actuator names
# init_joint_positions: initial joint positions (rad)
# init_joint_torques: initial joints torques (N*m)
# joint_velocities: initial joint velocities (rad/s)
joints:
  num_joints: 12

  joint_names: ["RL_hip_joint", "FL_hip_joint", "RR_hip_joint", "FR_hip_joint",
                "RL_thigh_joint", "FL_thigh_joint", "RR_thigh_joint", "FR_thigh_joint",
                "RL_calf_joint", "FL_calf_joint", "RR_calf_joint", "FR_calf_joint"]

  joint_actuator_names: ["RL_hip_motor", "RL_thigh_motor", "RL_calf_motor", 
                         "FL_hip_motor", "FL_thigh_motor", "FL_calf_motor",
                         "RR_hip_motor", "RR_thigh_motor", "RR_calf_motor",
                         "FR_hip_motor", "FR_thigh_motor", "FR_calf_motor"]

  # Maps to joint names
  init_joint_positions: [0.0, 0.0, 0.0, 0.0, 1.61, 1.61, 1.61, 1.61, -2.78, -2.78, -2.78, -2.78]
  
  # Maps to joint actuator names 
  init_joint_torques: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

joint_control:
  kff: [0.0, 0.0, 0.0]
  kp: [40.0, 40.0, 50.0]
  kd: [1.0, 1.0, 1.0]
  # kp: [30.0, 30.0, 30.0]
  # kd: [0.5, 0.5, 0.5]

# torque_min: minimum joint torque (N*m)
# torque_max: maximum joint torque (N*m)
# s_diagonal: diagonal weights on least squares (Ax-b)*S*(Ax-b)
# w_diagonal: diagonal weight on forces in fT*W*f in format f = [RL, FL, RR, FR] (fx,fy,fz)
# kff: feed forward gain on [vx_d, vy_d, m*g, roll_dot, pitch_dot, yaw_dot]
# kp_p: COM position Kp
# kp_w: COM orientation Kp
# kd_p: COM linear velocity Kd
# kd_w: COM angular velocity Kd
balance_control:
  torque_min: -20.0
  torque_max: 20.0

  # Standing 
  s_diagonal: [1.0, 1.0, 1.0, 10.0, 10.0, 5.0]
  # s_diagonal: [0.5, 0.5, 0.5, 20.0, 20.0, 10.0]
  w_diagonal: [0.00001]
  
  kff: [0.0, 0.0, 0.15, 0.0, 0.0, 0.0]
  # kp_p: [100.0, 100.0, 150.0]
  # kp_w: [3000.0, 3000.0, 3000.0]

  # kd_p: [50.0, 50.0, 50.0]
  # kd_w: [250.0, 250.0, 250.0]

  kp_p: [100.0, 100.0, 100.0]
  kp_w: [5000.0, 5000.0, 5000.0]

  kd_p: [50.0, 50.0, 50.0]
  kd_w: [500.0, 500.0, 500.0]


# Ib: moment of inertia in body frame (kg*m2)
# mass: total mass (kg)
# mu: coefficient of friction (kg*m/s^2)
# fzmin: absolute minimum z-axis ground reaction force (N)
# fzmax: absolute maximum z-axis ground reaction force (N)
dynamics: 
  Ib: [0.011253, 0.036203, 0.042673]
  mass: 11.0  
  mu: 0.8
  fzmin: 10.0 
  fzmax: 120.0
