# Teleop configuration for walking using PS4 joystick
teleop_twist_joy:
  axis_linear: 
    x: 1
    y: 0
  scale_linear:
    x: 0.5
    y: 0.5
  axis_angular:
    yaw: 3
  scale_angular:
    yaw: 0.5
  enable_button: 4
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
  dev: /dev/input/js0
