# Teleop configuration for stance control using PS4
teleop_twist_joy:
  axis_linear: 
    z: 4
  scale_linear:
    z: 0.5
  axis_angular:
    roll: 0
    pitch: 1
    yaw: 3
  scale_angular:
    roll: 0.5
    pitch: 0.5
    yaw: 0.5
  enable_button: 4
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
  dev: /dev/input/js0
