# Teleop configuration for PS4 joystick using the x-pad configuration.
# Walking 
# teleop_twist_joy:
#   axis_linear: 
#     x: 1
#     y: 0
#   scale_linear:
#     x: 0.5
#     y: 0.5
#   axis_angular:
#     yaw: 3
#   scale_angular:
#     yaw: 0.5
#   enable_button: 4
# Stance Control 
teleop_twist_joy:
  axis_linear: 
    z: 4
  scale_linear:
    z: 0.5
  axis_angular:
    roll: 0
    pitch: 1
    yaw: 3
  scale_angular:
    roll: 0.5
    pitch: 0.5
    yaw: 0.5
  enable_button: 4
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
  dev: /dev/input/js0
